left_front:
  - lf_hip_joint
  - lf_upper_leg_joint
  - lf_lower_leg_joint
  - rig_lf

right_front:
  - rf_hip_joint
  - rf_upper_leg_joint
  - rf_lower_leg_joint
  - rig_rf

left_hind:
  - lh_hip_joint
  - lh_upper_leg_joint
  - lh_lower_leg_joint
  - rig_lh

right_hind:
  - rh_hip_joint
  - rh_upper_leg_joint
  - rh_lower_leg_joint
  - rig_rh