base: base_link
left_front:
  - lf_hipp_1
  - lf_up_1
  - lf_low_1
  - lf_foot_1

right_front:
  - rf_hipp_1
  - rf_up_1
  - rf_low_1
  - rf_foot_1

left_hind:
  - lh_hipp_1
  - lh_up_1
  - lh_low_1
  - lh_foot_1

right_hind:
  - rh_hipp_1
  - rh_up_1
  - rh_low_1
  - rh_foot_1